name: Node.js CI

"on":
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn --immutable

      - name: Formatter
        run: yarn format:ci

      - name: Lint
        run: yarn lint

      - name: Build Packages
        run: BASE_PATH=/react-icons ./build-script.sh

      - uses: actions/upload-artifact@v3
        with:
          path: packages/_react-icons*/*.tgz

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/preview/out
        if: contains(github.ref, 'tags/')

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "packages/_react-icons*/*.tgz"
          bodyFile: "packages/react-icons/VERSIONS"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref, 'snapshot') }}
        if: contains(github.ref, 'tags/')

      - name: Publish react-icons
        if: contains(github.ref, 'tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish packages/_react-icons/*.tgz
